services:
  server:
    image: healthcrm.server
    env_file:
      - ${HOME}/Workspaces/HealthCRM/HealthCRM.Server.env
    pull_policy: build
    build:
      context: ./HealthCRM.Server
      dockerfile: Dockerfile
    container_name: server
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    mem_reservation: 256M
    ulimits:
      nofile:
        soft: 1024
        hard: 4096
    environment:
      - ASPNETCORE_URLS=https://+:5229
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/HealthCRM.Server.pfx
      - ASPNETCORE_ENVIRONMENT=Staging
      - SSLKEYLOGFILE=/Captures/kestrel-keys.log
    volumes:
      - ${HOME}/Projects/HealthCRM/HealthCRM.Server/Logs:/app/Logs
      - ${HOME}/Projects/HealthCRM/HealthCRM.DockerDebugging/Captures:/Captures 
    configs:
      - { source: server_appsettings, target: /app/appsettings.Staging.json }
    secrets:
      - { source: server_pfx, target: /https/HealthCRM.Server.pfx }
    networks:
      healthcrm-network:
        ipv4_address: 10.0.0.3
        aliases:
          - healthcrm.api.local
  
  client:
    image: healthcrm.client
    pull_policy: build
    build: 
      context: ./HealthCRM.Client
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - server
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ${HOME}/Projects/HealthCRM/HealthCRM.Client/Logs:/var/log/nginx
    configs:
      - { source: nginx_conf, target: /etc/nginx/nginx.conf }
    secrets:
      - { source: client_key, target: /etc/nginx/certs/HealthCRM.Client.key }
      - { source: client_pem, target: /etc/nginx/certs/HealthCRM.Client.pem }
      - { source: ca_pem, target: /etc/nginx/certs/HealthCRM.CA.pem }
    networks:
      healthcrm-network:
        ipv4_address: 10.0.0.2
        aliases:
          - healthcrm.local

  client.debug:
    image: healthcrm.debug
    pull_policy: build
    build:
      context: ./HealthCRM.DockerDebugging
      dockerfile: Dockerfile
    container_name: client.debug
    network_mode: "service:client"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${HOME}/Projects/HealthCRM/HealthCRM.DockerDebugging/Captures:/Captures
    secrets:
      - { source: ca_pem, target: HealthCRM.CA.pem }
    command: sleep infinity
    depends_on:
      - client
    profiles:
      - debug
  
  server.debug:
    image: healthcrm.debug
    pull_policy: build
    build:
      context: ./HealthCRM.DockerDebugging
      dockerfile: Dockerfile
    container_name: server.debug
    network_mode: "service:server"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${HOME}/Projects/HealthCRM/HealthCRM.DockerDebugging/Captures:/Captures
    secrets:
      - { source: ca_pem, target: HealthCRM.CA.pem }
    command: sleep infinity
    depends_on:
      - server
    profiles:
      - debug

networks:
  healthcrm-network:
    name: healthcrm-network
    driver: bridge
    ipam:
      driver: default
      config:
        - { subnet: 10.0.0.0/28, gateway: 10.0.0.1 }

configs:
  nginx_conf:
    file: ${HOME}/Projects/HealthCRM/HealthCRM.Client/staging.nginx.conf
  server_appsettings:
    file: ${HOME}/Projects/HealthCRM/HealthCRM.Server/appsettings.Staging.json

secrets:
  client_key:
    file: ${HOME}/Workspaces/HealthCRM/HealthCRM.Client.key
  client_pem:
    file: ${HOME}/Workspaces/HealthCRM/HealthCRM.Client.pem
  ca_pem:
    file: ${HOME}/Workspaces/HealthCRM/HealthCRM.CA.pem
  server_pfx:
    file: ${HOME}/Workspaces/HealthCRM/HealthCRM.Server.pfx