[req]
distinguished_name = req_distinguished_name
x509_extensions    = v3_ca
prompt             = no

[req_distinguished_name]
CN = HealthCRMCA

[v3_ca]
basicConstraints        = critical, CA:true, pathlen:0
keyUsage                = critical, keyCertSign, cRLSign
nameConstraints         = critical, @name_constraints
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid:always

[name_constraints]
permitted;DNS.1 = localhost
permitted;DNS.2 = healthcrm.local
permitted;DNS.3 = healthcrm.api.local
permitted;IP.1  = 127.0.0.1/255.255.255.255
permitted;IP.2  = 10.0.0.0/255.255.255.240